### ISSUE TITLE
New Logo For HTWG LSF Plan

### ISSUE THREAD

**Issue by zularizal** [GoneUp/Htwg_LsfPlan#2]
Hi i want to make a new logo for you, it's free, do you want it?

**Comment by GoneUp** [comment]
Yes, of course. The current is not that good (Well, I'm no designer). 
It just needs to be [adaptive](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) to fit the current google guideline.

**Comment by zularizal** [comment]
Okay, now i'm making it..

**Comment by zularizal** [comment]
It's an icon I've designed, Do u like it?
if you want a change about something, feel free to tell me.

![logo](https://user-images.githubusercontent.com/38547278/39327989-fcf80f04-49c3-11e8-99d1-3a769e6cd7a0.png)

**Comment by GoneUp** [comment]
I really like the foregorund icon with the badge on it. I would like to change the background color, it looks a bit to aggresive/bright to me. Could you tweak a bit?

**Comment by zularizal** [comment]
Which one do you like @GoneUp ?

![logo2](https://user-images.githubusercontent.com/38547278/39368761-ab675c5c-4a64-11e8-8150-57592877eeb4.png)

**Comment by GoneUp** [comment]
Sorry for the late response, totally forgot to answer. B1 looks great to me. Could you upload me the logo files somewhere?

**Comment by zularizal** [comment]
Okay, I've uploaded it, please check in this link

https://drive.google.com/open?id=1GRkG3eMZm_VQWv2QUuCdfkkxcEobRp-S

**Comment by zularizal** [comment]
And I've sent a pull request, please check #3

**Comment by GoneUp** [comment]
Thank you very much. I will update the actual icon and the playstore page.
